### ISSUE TITLE
Slight layout change with a future flow bugfix

### ISSUE THREAD

**Issue by luk3yx** [C-C-Minetest-Server/metadata_inspector#1]
Hi,

There's currently a bug in flow that stops it from taking a field's label into account when both a width and height are specified in the `gui.Field` element, shown by the screenshot of this mod in ContentDB:
![Screenshot](https://user-images.githubusercontent.com/3182651/215307243-1406830f-990a-487d-9eef-cd9a4e939d9c.png)

I plan on fixing this bug in flow, however if I do the "+" button in this mod would be expanded to fill the newly available space in the HBox:
![Screenshot](https://user-images.githubusercontent.com/3182651/215307220-d9c899ef-f222-42fc-a65a-b7c412c3711e.png)

To prevent this, you should just need to add `align_v = "bottom"` to the button's definition on line 70. https://github.com/C-C-Minetest-Server/metadata_inspector/blob/d33da79b391a0d4b59c8380445c5e5adbf32375a/init.lua#L70

**Comment by luk3yx** [comment]
@Emojigit Is it okay if I update flow with the bugfix I mentioned in this issue?

**Comment by Emojigit** [comment]
Done. Thank you for you suggestion.
